Repository Big-Bytez/cse110-fa21-group19, pull requests merged in 2021-12, with the labels that each got.

#119 made user portal and search page mobile
  source/components/CSS/thumbnail.css
  source/components/RecipeTile.css
  source/components/RecipleTile.html
  source/components/SearchBar.html
  source/home-page/assets/script.js
  source/home-page/index.html
  source/home-page/styles/style.css
  source/recipe-individual/index.html
  source/recipe-individual/individual.css
  source/recipe-individual/scripts/individualCustom.js
  source/search_page/assets/searchRecipe.js
  source/search_page/mini-recipe.html
  source/search_page/styles/style.css
  source/user-portal/index.html
  source/user-portal/styles/style.css
Labels: enhancement

#120 Shuffle button implementation
  source/home-page/assets/script.js
  source/home-page/index.html
  source/recipe-individual/index.html
  source/recipe-individual/scripts/individual.js
  source/search_page/assets/script.js
  source/search_page/index.html
  source/user-portal/scripts/upload.js
Labels: enhancement, home-page, recipe-page, search-page

#132 edited mobile styling
  source/home-page/styles/style.css
  source/recipe-individual/individual.css
  source/recipe-individual/scripts/individualCustom.js
  source/search_page/styles/style.css
  source/user-portal/styles/style.css
Labels: enhancement, styling

#133 fixed the api call
  source/home-page/assets/script.js
  source/recipe-individual/scripts/individual.js
  source/search_page/assets/script.js
  source/user-portal/scripts/upload.js
Labels: bug

#135 Adding text, fixing formatting
  source/home-page/index.html
  source/home-page/styles/style.css
  source/recipe-individual/index.html
  source/recipe-individual/individual.css
  source/search_page/index.html
  source/search_page/styles/style.css
  source/user-portal/index.html
  source/user-portal/styles/style.css
Labels: bug, enhancement
